### ISSUE TITLE
throwing an error with recent versions of ansible

### ISSUE THREAD

**Issue by fields** [rvm/rvm1-ansible#133]
I'm getting this error when trying to use ansible 2.2.0 or later:

TASK [rvm_io.rvm1-ruby : Install rubies] ***************************************
fatal: [172.20.38.156]: FAILED! => {"failed": true, "msg": "The conditional check 'rvm1_rubies and item.rc != 0' failed. The error was: error while evaluating conditional (rvm1_rubies and item.rc != 0): 'unicode object' has no attribute 'rc'\n\nThe error appears to have been in '/private/etc/ansible/roles/rvm_io.rvm1-ruby/tasks/rubies.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install rubies\n  ^ here\n"}

It works fine with ansible 2.1.0. I see a bump branch for the ansible version, but it hasn't been updated in months. Any idea when this will be ready?

Thanks!

**Comment by lpaulmp** [comment]
@fields Looks you are not using a correct galaxy, can you try with this one https://github.com/rvm/rvm1-ansible#installation.

**Comment by fields** [comment]
Thanks - I must have missed a notification that this changed and still had the old version installed.
